<?php echo $this->doctype(); 
   $templateURL = 'templates/v1/';
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        //->prependStylesheet($this->basePath($templateURL. 'css/style.css'))
                        //->prependStylesheet($this->basePath($templateURL. 'css/bootstrap-theme.min.css'))
                        //->prependStylesheet($this->basePath($templateURL. 'css/bootstrap.min.css'))
                        
                        
                        ->prependStylesheet($this->basePath($templateURL. 'assets/css/demo.css'))
                        ->prependStylesheet($this->basePath($templateURL. 'assets/css/get-shit-done.css'))
                        ->prependStylesheet($this->basePath($templateURL. 'bootstrap3/css/font-awesome.css'))
                        ->prependStylesheet($this->basePath($templateURL. 'bootstrap3/css/bootstrap.css'))
                        
                        
                        
                         ?>
                        

    
    <!--     Font Awesome     -->
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Grand+Hotel' rel='stylesheet' type='text/css'>

        <!-- Scripts -->
        <?php // echo $this->headScript()
//            ->prependFile($this->basePath($templateURL. 'js/bootstrap.min.js'))
//            ->prependFile($this->basePath($templateURL. 'js/jquery.min.js'))
//            ->prependFile($this->basePath($templateURL. 'js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
//            ->prependFile($this->basePath($templateURL. 'js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
//        ; ?>

    </head>
    <body>
        <?php echo $this->partial('layout/v1/header'); ?>
        <div class="main">
            <div class="container tim-container" style="max-width:800px; padding-top:100px">
               <h1 class="text-center">Awesome looking header <br> just for my friends<small class="subtitle">This is like a small motto before the story.</small></h1>
               <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
               <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>      
                   <!--     end extras -->        
            </div>
            <div class="space"></div>
        <!-- end container -->
        </div>
        <!-- end main -->
    </body>
    <script src="<?php echo $templateURL. 'jquery/jquery-1.10.2.js'?>" type="text/javascript"></script>
	<script src="<?php echo $templateURL. 'assets/js/jquery-ui-1.10.4.custom.min.js'?>" type="text/javascript"></script>

	<script src="<?php echo $templateURL. 'bootstrap3/js/bootstrap.js'?>" type="text/javascript"></script>
	<script src="<?php echo $templateURL. 'assets/js/gsdk-checkbox.js'?>"></script>
	<script src="<?php echo $templateURL. 'assets/js/gsdk-radio.js'?>"></script>
	<script src="<?php echo $templateURL. 'assets/js/gsdk-bootstrapswitch.js'?>"></script>
	<script src="<?php echo $templateURL. 'assets/js/get-shit-done.js'?>"></script>
	
    <script src="<?php echo $templateURL. 'assets/js/custom.js'?>"></script>
</html>
